### ISSUE TITLE
[Bug]: Problem with Turkish chars

### ISSUE THREAD

**Issue by onursimsek** [Karaca-Tech/string-mask#5]
### What happened?

Masking is incorrect when using Turkish characters in text.

### How to reproduce the bug

Example text: Onur Şimşek
Expect: O*** Ş*****
Actual: O*** Ş*******

there are extra two masking chars because Şimşek have two Turkish chars

### Package Version

latest

### PHP Version

8.2.10

### Which operating systems does with happen with?

Linux

**Comment by uutkukorkmaz** [comment]
Here, the root cause is the use of `strlen` in the processors. Since the `strlen` function doesn't count multibyte characters and the Turkish letters are multibyte, it seems an extra asterisk is added during the masking process. Will fix asap
